/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedIndicacoesRouteImport } from './routes/_authenticated/indicacoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteRouteImport } from './routes/_authenticated/configuracoes/route'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedInvestimentosIndexRouteImport } from './routes/_authenticated/investimentos.index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes/index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedInvestimentosSdrRouteImport } from './routes/_authenticated/investimentos.sdr'
import { Route as AuthenticatedInvestimentosReunioesRouteImport } from './routes/_authenticated/investimentos.reunioes'
import { Route as AuthenticatedInvestimentosQualificacaoRouteImport } from './routes/_authenticated/investimentos.qualificacao'
import { Route as AuthenticatedInvestimentosPipelineRouteImport } from './routes/_authenticated/investimentos.pipeline'
import { Route as AuthenticatedConfiguracoesPapeisRouteImport } from './routes/_authenticated/configuracoes/papeis'
import { Route as AuthenticatedConfiguracoesMetasRouteImport } from './routes/_authenticated/configuracoes/metas'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacoesRoute = AuthenticatedIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRouteRoute =
  AuthenticatedConfiguracoesRouteRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestimentosIndexRoute =
  AuthenticatedInvestimentosIndexRouteImport.update({
    id: '/investimentos/',
    path: '/investimentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracoesRouteRoute,
  } as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestimentosSdrRoute =
  AuthenticatedInvestimentosSdrRouteImport.update({
    id: '/investimentos/sdr',
    path: '/investimentos/sdr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestimentosReunioesRoute =
  AuthenticatedInvestimentosReunioesRouteImport.update({
    id: '/investimentos/reunioes',
    path: '/investimentos/reunioes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestimentosQualificacaoRoute =
  AuthenticatedInvestimentosQualificacaoRouteImport.update({
    id: '/investimentos/qualificacao',
    path: '/investimentos/qualificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestimentosPipelineRoute =
  AuthenticatedInvestimentosPipelineRouteImport.update({
    id: '/investimentos/pipeline',
    path: '/investimentos/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesPapeisRoute =
  AuthenticatedConfiguracoesPapeisRouteImport.update({
    id: '/papeis',
    path: '/papeis',
    getParentRoute: () => AuthenticatedConfiguracoesRouteRoute,
  } as any)
const AuthenticatedConfiguracoesMetasRoute =
  AuthenticatedConfiguracoesMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedConfiguracoesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/register': typeof RegisterRoute
  '/tv': typeof TvRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/configuracoes/metas': typeof AuthenticatedConfiguracoesMetasRoute
  '/configuracoes/papeis': typeof AuthenticatedConfiguracoesPapeisRoute
  '/investimentos/pipeline': typeof AuthenticatedInvestimentosPipelineRoute
  '/investimentos/qualificacao': typeof AuthenticatedInvestimentosQualificacaoRoute
  '/investimentos/reunioes': typeof AuthenticatedInvestimentosReunioesRoute
  '/investimentos/sdr': typeof AuthenticatedInvestimentosSdrRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/investimentos/': typeof AuthenticatedInvestimentosIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/register': typeof RegisterRoute
  '/tv': typeof TvRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/configuracoes/metas': typeof AuthenticatedConfiguracoesMetasRoute
  '/configuracoes/papeis': typeof AuthenticatedConfiguracoesPapeisRoute
  '/investimentos/pipeline': typeof AuthenticatedInvestimentosPipelineRoute
  '/investimentos/qualificacao': typeof AuthenticatedInvestimentosQualificacaoRoute
  '/investimentos/reunioes': typeof AuthenticatedInvestimentosReunioesRoute
  '/investimentos/sdr': typeof AuthenticatedInvestimentosSdrRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/investimentos': typeof AuthenticatedInvestimentosIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/register': typeof RegisterRoute
  '/tv': typeof TvRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/configuracoes/metas': typeof AuthenticatedConfiguracoesMetasRoute
  '/_authenticated/configuracoes/papeis': typeof AuthenticatedConfiguracoesPapeisRoute
  '/_authenticated/investimentos/pipeline': typeof AuthenticatedInvestimentosPipelineRoute
  '/_authenticated/investimentos/qualificacao': typeof AuthenticatedInvestimentosQualificacaoRoute
  '/_authenticated/investimentos/reunioes': typeof AuthenticatedInvestimentosReunioesRoute
  '/_authenticated/investimentos/sdr': typeof AuthenticatedInvestimentosSdrRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/investimentos/': typeof AuthenticatedInvestimentosIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/register'
    | '/tv'
    | '/configuracoes'
    | '/dashboard'
    | '/indicacoes'
    | '/vendas'
    | '/configuracoes/metas'
    | '/configuracoes/papeis'
    | '/investimentos/pipeline'
    | '/investimentos/qualificacao'
    | '/investimentos/reunioes'
    | '/investimentos/sdr'
    | '/leads/$id'
    | '/configuracoes/'
    | '/investimentos/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/register'
    | '/tv'
    | '/dashboard'
    | '/indicacoes'
    | '/vendas'
    | '/configuracoes/metas'
    | '/configuracoes/papeis'
    | '/investimentos/pipeline'
    | '/investimentos/qualificacao'
    | '/investimentos/reunioes'
    | '/investimentos/sdr'
    | '/leads/$id'
    | '/configuracoes'
    | '/investimentos'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/primeiro-acesso'
    | '/register'
    | '/tv'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/indicacoes'
    | '/_authenticated/vendas'
    | '/_authenticated/configuracoes/metas'
    | '/_authenticated/configuracoes/papeis'
    | '/_authenticated/investimentos/pipeline'
    | '/_authenticated/investimentos/qualificacao'
    | '/_authenticated/investimentos/reunioes'
    | '/_authenticated/investimentos/sdr'
    | '/_authenticated/leads/$id'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/investimentos/'
    | '/_authenticated/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  RegisterRoute: typeof RegisterRoute
  TvRoute: typeof TvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacoes': {
      id: '/_authenticated/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AuthenticatedIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos/': {
      id: '/_authenticated/investimentos/'
      path: '/investimentos'
      fullPath: '/investimentos/'
      preLoaderRoute: typeof AuthenticatedInvestimentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos/sdr': {
      id: '/_authenticated/investimentos/sdr'
      path: '/investimentos/sdr'
      fullPath: '/investimentos/sdr'
      preLoaderRoute: typeof AuthenticatedInvestimentosSdrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos/reunioes': {
      id: '/_authenticated/investimentos/reunioes'
      path: '/investimentos/reunioes'
      fullPath: '/investimentos/reunioes'
      preLoaderRoute: typeof AuthenticatedInvestimentosReunioesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos/qualificacao': {
      id: '/_authenticated/investimentos/qualificacao'
      path: '/investimentos/qualificacao'
      fullPath: '/investimentos/qualificacao'
      preLoaderRoute: typeof AuthenticatedInvestimentosQualificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos/pipeline': {
      id: '/_authenticated/investimentos/pipeline'
      path: '/investimentos/pipeline'
      fullPath: '/investimentos/pipeline'
      preLoaderRoute: typeof AuthenticatedInvestimentosPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/papeis': {
      id: '/_authenticated/configuracoes/papeis'
      path: '/papeis'
      fullPath: '/configuracoes/papeis'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPapeisRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRouteRoute
    }
    '/_authenticated/configuracoes/metas': {
      id: '/_authenticated/configuracoes/metas'
      path: '/metas'
      fullPath: '/configuracoes/metas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesMetasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRouteRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteRouteChildren {
  AuthenticatedConfiguracoesMetasRoute: typeof AuthenticatedConfiguracoesMetasRoute
  AuthenticatedConfiguracoesPapeisRoute: typeof AuthenticatedConfiguracoesPapeisRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedConfiguracoesRouteRouteChildren: AuthenticatedConfiguracoesRouteRouteChildren =
  {
    AuthenticatedConfiguracoesMetasRoute: AuthenticatedConfiguracoesMetasRoute,
    AuthenticatedConfiguracoesPapeisRoute:
      AuthenticatedConfiguracoesPapeisRoute,
    AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  }

const AuthenticatedConfiguracoesRouteRouteWithChildren =
  AuthenticatedConfiguracoesRouteRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRouteRoute: typeof AuthenticatedConfiguracoesRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndicacoesRoute: typeof AuthenticatedIndicacoesRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedInvestimentosPipelineRoute: typeof AuthenticatedInvestimentosPipelineRoute
  AuthenticatedInvestimentosQualificacaoRoute: typeof AuthenticatedInvestimentosQualificacaoRoute
  AuthenticatedInvestimentosReunioesRoute: typeof AuthenticatedInvestimentosReunioesRoute
  AuthenticatedInvestimentosSdrRoute: typeof AuthenticatedInvestimentosSdrRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedInvestimentosIndexRoute: typeof AuthenticatedInvestimentosIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRouteRoute:
    AuthenticatedConfiguracoesRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndicacoesRoute: AuthenticatedIndicacoesRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedInvestimentosPipelineRoute:
    AuthenticatedInvestimentosPipelineRoute,
  AuthenticatedInvestimentosQualificacaoRoute:
    AuthenticatedInvestimentosQualificacaoRoute,
  AuthenticatedInvestimentosReunioesRoute:
    AuthenticatedInvestimentosReunioesRoute,
  AuthenticatedInvestimentosSdrRoute: AuthenticatedInvestimentosSdrRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedInvestimentosIndexRoute: AuthenticatedInvestimentosIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  RegisterRoute: RegisterRoute,
  TvRoute: TvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
